name: ASMRBeanie
version: 1.0.0
main: me.mogubea.main.Main
bootstrapper: me.mogubea.bootstrap.Bootstrapper
description: Silly plugin for ASMR Community Server
author: Mogubea
website: https://asmrbeanie.com
api-version: '1.21.4'
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true